### ISSUE TITLE
Error closing result stream session id is null when running testng tests in parallel

### ISSUE THREAD

**Issue by deanml** [saucelabs/sauce-java#41]
Not sure why my session id is coming back as null but I do believe it has to do with the fact that I am running my testng tests in parallel with 22 different threads.  I am seeing the following error in the jenkins console when running my test classes using maven.  None of the test results are shown in the sauce labs UI as passed or failed, only "?" and complete.  I am using the listener in my base test class as shown here:

public class TestNGTestBase implements SauceOnDemandSessionIdProvider, SauceOnDemandAuthenticationProvider {

All my test classes extend my baseclass called TestNGTestBase and contain the annotation for adding the SauceOnDemandTestListener:

@Listeners({SauceOnDemandTestListener.class})
public class AcceptHintFromAllHintsPage extends TestNGTestBase {

The Jenkins console shows the following error for each test class that is executed:
SauceOnDemandSessionID=null job-name=AcceptHintFromAllHintsPage
May 12, 2016 12:20:57 PM com.saucelabs.saucerest.SauceREST closeInputStream
WARNING: Error closing result stream
java.io.FileNotFoundException: https://saucelabs.com/rest/v1/mldean/jobs/null
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1836)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at com.saucelabs.saucerest.SauceREST.closeInputStream(SauceREST.java:442)
	at com.saucelabs.saucerest.SauceREST.updateJobInfo(SauceREST.java:410)
	at com.saucelabs.testng.SauceOnDemandTestListener.markJobStatus(SauceOnDemandTestListener.java:115)
	at com.saucelabs.testng.SauceOnDemandTestListener.onTestSuccess(SauceOnDemandTestListener.java:142)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1899)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1879)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:778)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by deanml** [comment]
Parallelization was not the cause but rather improper termination of the remote web driver instance through driver.quit()
